### PR TITLE
Merging contribution from shpingalet007 to allow arguments 

### PR DESCRIPTION
**Pull request by shanegenschaw**
Merging https://github.com/Khan/pull-request-comment-trigger/pull/34.

With contributions from @shpingalet007  in https://github.com/shpingalet007/pr-commands

> ## Changes
> 1. **Added GitHub Actions input** - `allow_arguments: Boolean`. It enables/disables arguments parsing. It is set to `false` by default.
> 2. **Arguments parsing via double-asterisk marker** - script looks for `**` in trigger and considers the marked part of the comment as argument. Output to the `steps.check.outputs.arguments`. It doesn't do anything if `allow_arguments: false`.
> 3. **Add new example** - add job that enables debugging `#deploy on ** environment` comment.
> 
> ## Other changes
> * Replace npm **`@zeit/ncc`** to **`@vercel/ncc`** as it was deprecated.
> * Upload new action NCC build.
> * Documented everything in **`Readme.md`**.

### CODE REVIEW

**Comment by shpingalet007** [comment]
Looks good 👍

**Comment by shanegenschaw** [comment]
@shpingalet007 I noticed the `example.yml` workflow is failing due to "`The template is not valid`", any ideas? https://github.com/shanegenschaw/pull-request-comment-trigger/actions/runs/5093067003/jobs/9155209868#step:3:1

**Comment by shanegenschaw** [comment]
#deploy show me a rocket

**Comment by shanegenschaw** [comment]
test comment

**Comment by shanegenschaw** [comment]
#deploy test

**Comment by shanegenschaw** [comment]
#look

**Comment by shanegenschaw** [comment]
#deploy on ** environment

**Comment by shanegenschaw** [comment]
#deploy test

**Comment by shpingalet007** [comment]
> @shpingalet007 I noticed the `example.yml` workflow is failing due to "`The template is not valid`", any ideas? https://github.com/shanegenschaw/pull-request-comment-trigger/actions/runs/5093067003/jobs/9155209868#step:3:1 

Seems like API access error as responds with 403, but no idea why. I'll look into it soon

**Comment by shanegenschaw** [comment]
#look

**Comment by shanegenschaw** [comment]
#deploy test

**Comment by shanegenschaw** [comment]
#deploy on ** environment test

**Comment by shanegenschaw** [comment]
> 

I didn't have the repo setup to allow GitHub Actions to post comments, I've fixed that issue so the access errors are gone.
GHA still doesn't like the template string, here's a more recent run: https://github.com/shanegenschaw/pull-request-comment-trigger/actions/runs/5093459388/jobs/9156082798#step:3:1

It's really not a blocker IMO since it is just in the example workflow, and shouldn't break the action itself. Just would be nice to not trip up future contributions.

**Comment by shpingalet007** [comment]
#deploy on dev environment

**Comment by shpingalet007** [comment]
@shanegenschaw I see... Looks like some unhandled error. The asterisks in the example command are a wildcard for a word. That's why it breaks if we put there **. However, something is wrong here.

The command `#deploy on dev environment` does the thing. Look into the [run#5093533819](https://github.com/shanegenschaw/pull-request-comment-trigger/actions/runs/5093533819)

**Comment by shanegenschaw** [comment]
@shpingalet007 gotcha, user error on my part then 😄 
I'm going to go ahead and merge this, thanks for the collaboration and quick replies!

**Comment by shpingalet007** [comment]
Okay @shanegenschaw 😀👍 Happy to collaborate on that, it's a pleasure. Anyway, I'll look into that next days and update the mainstream PR. I will let you know to update that on your fork when it would be ready. Have a nice weekend!

**Update:** I have a test repo where I was using this action charged with arguments. I will leave here the link for you if you would like to look for a reference on what can be done with this PR accepted shpingalet007/pr-deployments/pull/1

**Pull request merged**
